namespace Estacionamiento.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PriceAdded4 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Articuloes", "TipoArticuloID", c => c.Int(nullable: false));
            AddColumn("dbo.Beneficios", "TipoBeneficioID", c => c.Int(nullable: false));
            AddColumn("dbo.Boletas", "ClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Boletas", "ArticuloID", c => c.Int(nullable: false));
            AddColumn("dbo.Boletas", "TipoPagoID", c => c.Int(nullable: false));
            AddColumn("dbo.Clientes", "TipoClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Clientes", "BeneficioID", c => c.Int(nullable: false));
            AddColumn("dbo.Distritoes", "SedeEstacionamientoID", c => c.Int(nullable: false));
            AddColumn("dbo.Empleadoes", "TipoEmpleadoID", c => c.String());
            AddColumn("dbo.Empleadoes", "TipoEstacionamientoID", c => c.String());
            AddColumn("dbo.Empleadoes", "TipoEmpleado_TipoEmpleadoID", c => c.Int());
            AddColumn("dbo.Empleadoes", "TipoEstacionamiento_TipoEstacionamientoID", c => c.Int());
            AddColumn("dbo.Eventoes", "TipoEventoID", c => c.Int(nullable: false));
            AddColumn("dbo.Eventoes", "ClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Eventoes", "SedeID", c => c.Int(nullable: false));
            AddColumn("dbo.Eventoes", "Fecha", c => c.DateTime(nullable: false));
            AddColumn("dbo.Eventoes", "SedeEstacionamiento_SedeEstacionamientoID", c => c.Int());
            AddColumn("dbo.GestionReclamoes", "ClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Publicidads", "ParkeoID", c => c.String());
            AddColumn("dbo.Publicidads", "ClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Publicidads", "Fecha", c => c.DateTime(nullable: false));
            AddColumn("dbo.Publicidads", "Parkeo_ParkeoID", c => c.Int());
            AddColumn("dbo.TarjetaPrepagoes", "ClienteID", c => c.String());
            AddColumn("dbo.TarjetaPrepagoes", "Cliente_ClienteID", c => c.Int());
            AddColumn("dbo.TipoEstacionamientoes", "ParkeoID", c => c.String());
            AddColumn("dbo.TipoEstacionamientoes", "Parkeo_ParkeoID", c => c.Int());
            AddColumn("dbo.UsoEstacionamientoes", "SedeEstacionamientoID", c => c.Int(nullable: false));
            AddColumn("dbo.ValetParkings", "UsoEstacionamientoID", c => c.String());
            AddColumn("dbo.ValetParkings", "ParkeoID", c => c.String());
            AddColumn("dbo.ValetParkings", "Parkeo_ParkeoID", c => c.Int());
            AddColumn("dbo.ValetParkings", "UsoEstacionamiento_UsoEstacionamientoID", c => c.Int());
            AddColumn("dbo.Vehiculoes", "TipoVehiculoID", c => c.String());
            AddColumn("dbo.Vehiculoes", "TipoVehiculo_TipoVehiculoID", c => c.Int());
            CreateIndex("dbo.Articuloes", "TipoArticuloID");
            CreateIndex("dbo.Beneficios", "TipoBeneficioID");
            CreateIndex("dbo.Boletas", "ClienteID");
            CreateIndex("dbo.Boletas", "ArticuloID");
            CreateIndex("dbo.Boletas", "TipoPagoID");
            CreateIndex("dbo.Clientes", "TipoClienteID");
            CreateIndex("dbo.Clientes", "BeneficioID");
            CreateIndex("dbo.Distritoes", "SedeEstacionamientoID");
            CreateIndex("dbo.Empleadoes", "TipoEmpleado_TipoEmpleadoID");
            CreateIndex("dbo.Empleadoes", "TipoEstacionamiento_TipoEstacionamientoID");
            CreateIndex("dbo.TipoEstacionamientoes", "Parkeo_ParkeoID");
            CreateIndex("dbo.Eventoes", "TipoEventoID");
            CreateIndex("dbo.Eventoes", "ClienteID");
            CreateIndex("dbo.Eventoes", "SedeEstacionamiento_SedeEstacionamientoID");
            CreateIndex("dbo.GestionReclamoes", "ClienteID");
            CreateIndex("dbo.Publicidads", "ClienteID");
            CreateIndex("dbo.Publicidads", "Parkeo_ParkeoID");
            CreateIndex("dbo.TarjetaPrepagoes", "Cliente_ClienteID");
            CreateIndex("dbo.UsoEstacionamientoes", "SedeEstacionamientoID");
            CreateIndex("dbo.ValetParkings", "Parkeo_ParkeoID");
            CreateIndex("dbo.ValetParkings", "UsoEstacionamiento_UsoEstacionamientoID");
            CreateIndex("dbo.Vehiculoes", "TipoVehiculo_TipoVehiculoID");
            AddForeignKey("dbo.Articuloes", "TipoArticuloID", "dbo.TipoArticuloes", "TipoArticuloID", cascadeDelete: true);
            AddForeignKey("dbo.Beneficios", "TipoBeneficioID", "dbo.TipoBeneficios", "TipoBeneficioID", cascadeDelete: true);
            AddForeignKey("dbo.Boletas", "ArticuloID", "dbo.Articuloes", "ArticuloID", cascadeDelete: true);
            AddForeignKey("dbo.Clientes", "BeneficioID", "dbo.Beneficios", "BeneficioID", cascadeDelete: true);
            AddForeignKey("dbo.Clientes", "TipoClienteID", "dbo.TipoClientes", "TipoClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Boletas", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Boletas", "TipoPagoID", "dbo.TipoPagoes", "TipoPagoID", cascadeDelete: true);
            AddForeignKey("dbo.Distritoes", "SedeEstacionamientoID", "dbo.SedeEstacionamientoes", "SedeEstacionamientoID", cascadeDelete: true);
            AddForeignKey("dbo.Empleadoes", "TipoEmpleado_TipoEmpleadoID", "dbo.TipoEmpleadoes", "TipoEmpleadoID");
            AddForeignKey("dbo.TipoEstacionamientoes", "Parkeo_ParkeoID", "dbo.Parkeos", "ParkeoID");
            AddForeignKey("dbo.Empleadoes", "TipoEstacionamiento_TipoEstacionamientoID", "dbo.TipoEstacionamientoes", "TipoEstacionamientoID");
            AddForeignKey("dbo.Eventoes", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Eventoes", "SedeEstacionamiento_SedeEstacionamientoID", "dbo.SedeEstacionamientoes", "SedeEstacionamientoID");
            AddForeignKey("dbo.Eventoes", "TipoEventoID", "dbo.TipoEventoes", "TipoEventoID", cascadeDelete: true);
            AddForeignKey("dbo.GestionReclamoes", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Publicidads", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Publicidads", "Parkeo_ParkeoID", "dbo.Parkeos", "ParkeoID");
            AddForeignKey("dbo.TarjetaPrepagoes", "Cliente_ClienteID", "dbo.Clientes", "ClienteID");
            AddForeignKey("dbo.UsoEstacionamientoes", "SedeEstacionamientoID", "dbo.SedeEstacionamientoes", "SedeEstacionamientoID", cascadeDelete: true);
            AddForeignKey("dbo.ValetParkings", "Parkeo_ParkeoID", "dbo.Parkeos", "ParkeoID");
            AddForeignKey("dbo.ValetParkings", "UsoEstacionamiento_UsoEstacionamientoID", "dbo.UsoEstacionamientoes", "UsoEstacionamientoID");
            AddForeignKey("dbo.Vehiculoes", "TipoVehiculo_TipoVehiculoID", "dbo.TipoVehiculoes", "TipoVehiculoID");
            DropColumn("dbo.Articuloes", "Precio");
            DropColumn("dbo.UsoEstacionamientoes", "SedeID");
        }
        
        public override void Down()
        {
            AddColumn("dbo.UsoEstacionamientoes", "SedeID", c => c.Int(nullable: false));
            AddColumn("dbo.Articuloes", "Precio", c => c.Double(nullable: false));
            DropForeignKey("dbo.Vehiculoes", "TipoVehiculo_TipoVehiculoID", "dbo.TipoVehiculoes");
            DropForeignKey("dbo.ValetParkings", "UsoEstacionamiento_UsoEstacionamientoID", "dbo.UsoEstacionamientoes");
            DropForeignKey("dbo.ValetParkings", "Parkeo_ParkeoID", "dbo.Parkeos");
            DropForeignKey("dbo.UsoEstacionamientoes", "SedeEstacionamientoID", "dbo.SedeEstacionamientoes");
            DropForeignKey("dbo.TarjetaPrepagoes", "Cliente_ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Publicidads", "Parkeo_ParkeoID", "dbo.Parkeos");
            DropForeignKey("dbo.Publicidads", "ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.GestionReclamoes", "ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Eventoes", "TipoEventoID", "dbo.TipoEventoes");
            DropForeignKey("dbo.Eventoes", "SedeEstacionamiento_SedeEstacionamientoID", "dbo.SedeEstacionamientoes");
            DropForeignKey("dbo.Eventoes", "ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Empleadoes", "TipoEstacionamiento_TipoEstacionamientoID", "dbo.TipoEstacionamientoes");
            DropForeignKey("dbo.TipoEstacionamientoes", "Parkeo_ParkeoID", "dbo.Parkeos");
            DropForeignKey("dbo.Empleadoes", "TipoEmpleado_TipoEmpleadoID", "dbo.TipoEmpleadoes");
            DropForeignKey("dbo.Distritoes", "SedeEstacionamientoID", "dbo.SedeEstacionamientoes");
            DropForeignKey("dbo.Boletas", "TipoPagoID", "dbo.TipoPagoes");
            DropForeignKey("dbo.Boletas", "ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Clientes", "TipoClienteID", "dbo.TipoClientes");
            DropForeignKey("dbo.Clientes", "BeneficioID", "dbo.Beneficios");
            DropForeignKey("dbo.Boletas", "ArticuloID", "dbo.Articuloes");
            DropForeignKey("dbo.Beneficios", "TipoBeneficioID", "dbo.TipoBeneficios");
            DropForeignKey("dbo.Articuloes", "TipoArticuloID", "dbo.TipoArticuloes");
            DropIndex("dbo.Vehiculoes", new[] { "TipoVehiculo_TipoVehiculoID" });
            DropIndex("dbo.ValetParkings", new[] { "UsoEstacionamiento_UsoEstacionamientoID" });
            DropIndex("dbo.ValetParkings", new[] { "Parkeo_ParkeoID" });
            DropIndex("dbo.UsoEstacionamientoes", new[] { "SedeEstacionamientoID" });
            DropIndex("dbo.TarjetaPrepagoes", new[] { "Cliente_ClienteID" });
            DropIndex("dbo.Publicidads", new[] { "Parkeo_ParkeoID" });
            DropIndex("dbo.Publicidads", new[] { "ClienteID" });
            DropIndex("dbo.GestionReclamoes", new[] { "ClienteID" });
            DropIndex("dbo.Eventoes", new[] { "SedeEstacionamiento_SedeEstacionamientoID" });
            DropIndex("dbo.Eventoes", new[] { "ClienteID" });
            DropIndex("dbo.Eventoes", new[] { "TipoEventoID" });
            DropIndex("dbo.TipoEstacionamientoes", new[] { "Parkeo_ParkeoID" });
            DropIndex("dbo.Empleadoes", new[] { "TipoEstacionamiento_TipoEstacionamientoID" });
            DropIndex("dbo.Empleadoes", new[] { "TipoEmpleado_TipoEmpleadoID" });
            DropIndex("dbo.Distritoes", new[] { "SedeEstacionamientoID" });
            DropIndex("dbo.Clientes", new[] { "BeneficioID" });
            DropIndex("dbo.Clientes", new[] { "TipoClienteID" });
            DropIndex("dbo.Boletas", new[] { "TipoPagoID" });
            DropIndex("dbo.Boletas", new[] { "ArticuloID" });
            DropIndex("dbo.Boletas", new[] { "ClienteID" });
            DropIndex("dbo.Beneficios", new[] { "TipoBeneficioID" });
            DropIndex("dbo.Articuloes", new[] { "TipoArticuloID" });
            DropColumn("dbo.Vehiculoes", "TipoVehiculo_TipoVehiculoID");
            DropColumn("dbo.Vehiculoes", "TipoVehiculoID");
            DropColumn("dbo.ValetParkings", "UsoEstacionamiento_UsoEstacionamientoID");
            DropColumn("dbo.ValetParkings", "Parkeo_ParkeoID");
            DropColumn("dbo.ValetParkings", "ParkeoID");
            DropColumn("dbo.ValetParkings", "UsoEstacionamientoID");
            DropColumn("dbo.UsoEstacionamientoes", "SedeEstacionamientoID");
            DropColumn("dbo.TipoEstacionamientoes", "Parkeo_ParkeoID");
            DropColumn("dbo.TipoEstacionamientoes", "ParkeoID");
            DropColumn("dbo.TarjetaPrepagoes", "Cliente_ClienteID");
            DropColumn("dbo.TarjetaPrepagoes", "ClienteID");
            DropColumn("dbo.Publicidads", "Parkeo_ParkeoID");
            DropColumn("dbo.Publicidads", "Fecha");
            DropColumn("dbo.Publicidads", "ClienteID");
            DropColumn("dbo.Publicidads", "ParkeoID");
            DropColumn("dbo.GestionReclamoes", "ClienteID");
            DropColumn("dbo.Eventoes", "SedeEstacionamiento_SedeEstacionamientoID");
            DropColumn("dbo.Eventoes", "Fecha");
            DropColumn("dbo.Eventoes", "SedeID");
            DropColumn("dbo.Eventoes", "ClienteID");
            DropColumn("dbo.Eventoes", "TipoEventoID");
            DropColumn("dbo.Empleadoes", "TipoEstacionamiento_TipoEstacionamientoID");
            DropColumn("dbo.Empleadoes", "TipoEmpleado_TipoEmpleadoID");
            DropColumn("dbo.Empleadoes", "TipoEstacionamientoID");
            DropColumn("dbo.Empleadoes", "TipoEmpleadoID");
            DropColumn("dbo.Distritoes", "SedeEstacionamientoID");
            DropColumn("dbo.Clientes", "BeneficioID");
            DropColumn("dbo.Clientes", "TipoClienteID");
            DropColumn("dbo.Boletas", "TipoPagoID");
            DropColumn("dbo.Boletas", "ArticuloID");
            DropColumn("dbo.Boletas", "ClienteID");
            DropColumn("dbo.Beneficios", "TipoBeneficioID");
            DropColumn("dbo.Articuloes", "TipoArticuloID");
        }
    }
}
